# Generated by Django 5.1.1 on 2024-10-07 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministracjaOsiedla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, max_length=100, null=True)),
                ('ulica', models.CharField(blank=True, max_length=100, null=True)),
                ('telefon', models.CharField(blank=True, max_length=15, null=True)),
                ('email_administracja', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Administracja Osiedla',
                'verbose_name_plural': 'Administracje Osiedli',
            },
        ),
        migrations.CreateModel(
            name='Spoldzielnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
                ('miasto', models.CharField(max_length=100)),
                ('ulica', models.CharField(max_length=100)),
                ('kod', models.CharField(max_length=10)),
                ('rok_zalozenia', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('strona_www', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Spółdzielnia',
                'verbose_name_plural': 'Spółdzielnie',
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_administrator', models.CharField(blank=True, max_length=100, null=True)),
                ('nazwisko_administrator', models.CharField(blank=True, max_length=100, null=True)),
                ('email_administrator', models.EmailField(blank=True, max_length=254, null=True)),
                ('komorka_administrator', models.CharField(blank=True, max_length=15, null=True)),
                ('telefon_stacjonarny_administrator', models.CharField(blank=True, max_length=15, null=True)),
                ('osiedle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administratorzy', to='panel.administracjaosiedla')),
            ],
            options={
                'verbose_name': 'Administrator',
                'verbose_name_plural': 'Administrator',
            },
        ),
        migrations.CreateModel(
            name='Budynek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indeks', models.CharField(max_length=10, unique=True)),
                ('ulica', models.CharField(max_length=100)),
                ('kod', models.CharField(max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='budynki_foto/')),
                ('rok_budowy', models.IntegerField(blank=True, null=True)),
                ('obreb', models.CharField(blank=True, max_length=100, null=True)),
                ('dzialka', models.CharField(blank=True, max_length=50, null=True)),
                ('laczna_powierzchnia_dzialki', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('powierzchnia_wspolna_budynku', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('osiedle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budynki', to='panel.administracjaosiedla')),
            ],
            options={
                'verbose_name': 'Budynek',
                'verbose_name_plural': 'Budynki',
            },
        ),
        migrations.CreateModel(
            name='Energetyka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okres_rozliczeniowy', models.CharField(max_length=255, verbose_name='Okres rozliczeniowy')),
                ('termin_legalizacji_wodomierzy', models.DateField(blank=True, null=True, verbose_name='Termin legalizacji wodomierzy')),
                ('uwagi_legalizacja_wodomierzy', models.TextField(blank=True, null=True, verbose_name='Uwagi legalizacja wodomierzy')),
                ('wymiana_baterii', models.DateField(blank=True, null=True, verbose_name='Wymiana baterii')),
                ('uwagi_wymiana_baterii', models.TextField(blank=True, null=True, verbose_name='Uwagi wymiana baterii')),
                ('budynek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energetyka', to='panel.budynek')),
            ],
            options={
                'verbose_name': 'Energetyka',
                'verbose_name_plural': 'Energetyka',
            },
        ),
        migrations.CreateModel(
            name='Finanse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundusz_remontowy', models.CharField(blank=True, max_length=50, null=True)),
                ('zadluzenie_budynku', models.CharField(blank=True, max_length=50, null=True)),
                ('budynek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finanse', to='panel.budynek')),
            ],
            options={
                'verbose_name': 'Finanse',
                'verbose_name_plural': 'Finanse',
            },
        ),
        migrations.CreateModel(
            name='Kierownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_kierownik', models.CharField(blank=True, max_length=100, null=True)),
                ('nazwisko_kierownik', models.CharField(blank=True, max_length=100, null=True)),
                ('imie_zastepca', models.CharField(blank=True, max_length=100, null=True)),
                ('nazwisko_zastepca', models.CharField(blank=True, max_length=100, null=True)),
                ('email_kierownik', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefon_kierownik', models.CharField(blank=True, max_length=15, null=True)),
                ('osiedle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kierownicy', to='panel.administracjaosiedla')),
            ],
            options={
                'verbose_name': 'Kierownik',
                'verbose_name_plural': 'Kierownik',
            },
        ),
        migrations.AddField(
            model_name='budynek',
            name='kierownik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budynki', to='panel.kierownik'),
        ),
        migrations.CreateModel(
            name='Przeglady',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planowany_przeglad_kominiarski', models.CharField(blank=True, max_length=255, null=True, verbose_name='Planowany przegląd kominiarski')),
                ('planowany_przeglad_gazowy', models.CharField(blank=True, max_length=255, null=True, verbose_name='Planowany przegląd gazowy')),
                ('planowany_przeglad_roczny_budynku', models.CharField(blank=True, max_length=255, null=True, verbose_name='Planowany roczny przegląd budynku')),
                ('planowany_przeglad_piecioletni_budynku', models.CharField(blank=True, max_length=255, null=True, verbose_name='Planowany pięcioletni przegląd budynku')),
                ('planowany_przeglad_piecioletni_gazowy', models.CharField(blank=True, max_length=255, null=True, verbose_name='Planowany pięcioletni przegląd gazowy')),
                ('aktualny_przeglad_kominiarski', models.CharField(blank=True, max_length=255, null=True, verbose_name='Aktualny przegląd kominiarski')),
                ('aktualny_przeglad_gazowy', models.CharField(blank=True, max_length=255, null=True, verbose_name='Aktualny przegląd gazowy')),
                ('aktualny_przeglad_roczny_budynku', models.CharField(blank=True, max_length=255, null=True, verbose_name='Aktualny roczny przegląd budynku')),
                ('aktualny_przeglad_piecioletni_budynku', models.CharField(blank=True, max_length=255, null=True, verbose_name='Aktualny pięcioletni przegląd budynku')),
                ('aktualny_przeglad_piecioletni_gazowy', models.CharField(blank=True, max_length=255, null=True, verbose_name='Aktualny pięcioletni przegląd gazowy')),
                ('budynek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='przeglady', to='panel.budynek')),
            ],
            options={
                'verbose_name': 'Przeglądy',
                'verbose_name_plural': 'Przeglądy',
            },
        ),
        migrations.CreateModel(
            name='Remonty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wykonawca', models.CharField(max_length=100)),
                ('opis_remontu', models.TextField()),
                ('poczatek_prac', models.DateField()),
                ('koniec_prac', models.DateField(blank=True, null=True)),
                ('uchwala', models.FileField(blank=True, null=True, upload_to='uchwaly/')),
                ('ankieta', models.FileField(blank=True, null=True, upload_to='ankiety/')),
                ('budynek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remonty', to='panel.budynek')),
            ],
            options={
                'verbose_name': 'Remonty',
                'verbose_name_plural': 'Remonty',
            },
        ),
        migrations.CreateModel(
            name='Smieci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styczen', models.PositiveIntegerField(blank=True, default=0)),
                ('luty', models.PositiveIntegerField(blank=True, default=0)),
                ('marzec', models.PositiveIntegerField(blank=True, default=0)),
                ('kwiecien', models.PositiveIntegerField(blank=True, default=0)),
                ('maj', models.PositiveIntegerField(blank=True, default=0)),
                ('czerwiec', models.PositiveIntegerField(blank=True, default=0)),
                ('lipiec', models.PositiveIntegerField(blank=True, default=0)),
                ('sierpien', models.PositiveIntegerField(blank=True, default=0)),
                ('wrzesien', models.PositiveIntegerField(blank=True, default=0)),
                ('pazdziernik', models.PositiveIntegerField(blank=True, default=0)),
                ('listopad', models.PositiveIntegerField(blank=True, default=0)),
                ('grudzien', models.PositiveIntegerField(blank=True, default=0)),
                ('budynek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smieci', to='panel.budynek')),
            ],
            options={
                'verbose_name': 'Śmieci',
                'verbose_name_plural': 'Śmieci',
            },
        ),
        migrations.AddField(
            model_name='budynek',
            name='spoldzielnia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budynki', to='panel.spoldzielnia'),
        ),
        migrations.AddField(
            model_name='administracjaosiedla',
            name='spoldzielnia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administracje', to='panel.spoldzielnia'),
        ),
    ]
