# Generated by Django 5.1.1 on 2024-10-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spoldzielnia',
            options={'verbose_name': 'Spółdzielnia', 'verbose_name_plural': 'Spółdzielnia'},
        ),
        migrations.AlterField(
            model_name='budynek',
            name='indeks',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
