# Generated by Django 5.1.1 on 2024-10-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_spoldzielnia_options_alter_budynek_indeks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smieci',
            name='czerwiec',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Czerwiec'),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='grudzien',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Grudzień'),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='kwiecien',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kwiecień'),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='lipiec',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Lipiec'),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='listopad',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Listopad'),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='luty',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Luty'),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='maj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Maj'),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='marzec',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Marzec'),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='pazdziernik',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Październik'),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='sierpien',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sierpień'),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='styczen',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Styczeń'),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='wrzesien',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Wrzesień'),
        ),
    ]
