# Generated by Django 5.1.1 on 2024-10-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_smieci_czerwiec_alter_smieci_grudzien_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smieci',
            name='budynek',
        ),
        migrations.AddField(
            model_name='smieci',
            name='plik_importu',
            field=models.FileField(blank=True, null=True, upload_to='smieci_importy/'),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='czerwiec',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='grudzien',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='kwiecien',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='lipiec',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='listopad',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='luty',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='maj',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='marzec',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='pazdziernik',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='sierpien',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='styczen',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='wrzesien',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
