# Generated by Django 5.1.1 on 2024-10-07 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_remove_smieci_budynek_smieci_plik_importu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smieci',
            name='budynek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smieci', to='panel.budynek'),
        ),
    ]
