# Generated by Django 5.1.1 on 2024-10-09 17:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_smieci_budynek'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalKierownik',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('imie_kierownik', models.CharField(blank=True, max_length=100, null=True)),
                ('nazwisko_kierownik', models.CharField(blank=True, max_length=100, null=True)),
                ('imie_zastepca', models.CharField(blank=True, max_length=100, null=True)),
                ('nazwisko_zastepca', models.CharField(blank=True, max_length=100, null=True)),
                ('email_kierownik', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefon_kierownik', models.CharField(blank=True, max_length=15, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('osiedle', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='panel.administracjaosiedla')),
            ],
            options={
                'verbose_name': 'historical Kierownik',
                'verbose_name_plural': 'historical Kierownik',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
