# Generated by Django 5.1.1 on 2024-10-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_historicalkierownik'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalKierownik',
        ),
    ]
