# Generated by Django 5.1.1 on 2024-10-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_historicalkierownik'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoldzielnia',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spoldzielnia',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spoldzielnia',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
