# Generated by Django 5.1.1 on 2024-10-10 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_historicaladministrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='budynek',
            name='administrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budynki', to='panel.administrator'),
        ),
    ]
