# Generated by Django 5.1.1 on 2024-10-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_budynek_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='budynek',
            name='telefon_osiedla',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
