# Generated by Django 5.1.1 on 2024-10-10 20:19

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_alter_budynek_osiedle_alter_budynek_spoldzielnia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBudynek',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('indeks', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('ulica', models.CharField(max_length=100)),
                ('kod', models.CharField(max_length=10)),
                ('foto', models.TextField(blank=True, max_length=100, null=True)),
                ('rok_budowy', models.IntegerField(blank=True, null=True)),
                ('telefon_osiedla', models.CharField(blank=True, max_length=20, null=True)),
                ('obreb', models.CharField(blank=True, max_length=100, null=True)),
                ('dzialka', models.CharField(blank=True, max_length=50, null=True)),
                ('laczna_powierzchnia_dzialki', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('powierzchnia_wspolna_budynku', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('administrator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='panel.administrator')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kierownik', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='panel.kierownik')),
                ('osiedle', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='panel.administracjaosiedla')),
                ('spoldzielnia', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='panel.spoldzielnia')),
            ],
            options={
                'verbose_name': 'historical Budynek',
                'verbose_name_plural': 'historical Budynki',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
