# Generated by Django 5.1.1 on 2024-10-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_historicaladministracjaosiedla_historicalenergetyka_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energetyka',
            name='termin_legalizacji_wodomierzy',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Termin legalizacji wodomierzy'),
        ),
        migrations.AlterField(
            model_name='energetyka',
            name='wymiana_baterii',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Wymiana baterii'),
        ),
        migrations.AlterField(
            model_name='historicalenergetyka',
            name='termin_legalizacji_wodomierzy',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Termin legalizacji wodomierzy'),
        ),
        migrations.AlterField(
            model_name='historicalenergetyka',
            name='wymiana_baterii',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Wymiana baterii'),
        ),
        migrations.AlterField(
            model_name='historicalremonty',
            name='wykonawca',
            field=models.CharField(max_length=100, verbose_name='Wykonawca'),
        ),
        migrations.AlterField(
            model_name='remonty',
            name='wykonawca',
            field=models.CharField(max_length=100, verbose_name='Wykonawca'),
        ),
    ]
