# Generated by Django 5.1.1 on 2024-10-13 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0017_alter_energetyka_termin_legalizacji_wodomierzy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energetyka',
            old_name='okres_rozliczeniowy',
            new_name='termin_podzielniki',
        ),
        migrations.RenameField(
            model_name='historicalenergetyka',
            old_name='okres_rozliczeniowy',
            new_name='termin_podzielniki',
        ),
    ]
