# Generated by Django 5.1.1 on 2024-10-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0018_rename_okres_rozliczeniowy_energetyka_termin_podzielniki_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='foto_administrator',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='historicaladministrator',
            name='foto_administrator',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalkierownik',
            name='foto_kierownik',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kierownik',
            name='foto_kierownik',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
