# Generated by Django 5.1.1 on 2024-10-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0019_administrator_foto_administrator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budynek',
            name='kod',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbudynek',
            name='kod',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
