# Generated by Django 5.1.1 on 2024-10-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0021_alter_budynek_laczna_powierzchnia_dzialki_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budynek',
            name='rok_budowy',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbudynek',
            name='rok_budowy',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
