# Generated by Django 5.1.1 on 2024-10-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0022_alter_budynek_rok_budowy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsmieci',
            name='plik_importu',
        ),
        migrations.RemoveField(
            model_name='smieci',
            name='plik_importu',
        ),
        migrations.AlterField(
            model_name='historicalsmieci',
            name='czerwiec',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsmieci',
            name='grudzien',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsmieci',
            name='kwiecien',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsmieci',
            name='lipiec',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsmieci',
            name='listopad',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsmieci',
            name='luty',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsmieci',
            name='maj',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsmieci',
            name='marzec',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsmieci',
            name='pazdziernik',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsmieci',
            name='sierpien',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsmieci',
            name='styczen',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsmieci',
            name='wrzesien',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='czerwiec',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='grudzien',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='kwiecien',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='lipiec',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='listopad',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='luty',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='maj',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='marzec',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='pazdziernik',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='sierpien',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='styczen',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smieci',
            name='wrzesien',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
