# Generated by Django 5.1.1 on 2024-10-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0023_remove_historicalsmieci_plik_importu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalremonty',
            name='poczatek_prac',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remonty',
            name='poczatek_prac',
            field=models.DateField(blank=True, null=True),
        ),
    ]
