# Generated by Django 5.1.1 on 2024-10-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0024_alter_historicalremonty_poczatek_prac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalremonty',
            name='opis_remontu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalremonty',
            name='wykonawca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Wykonawca'),
        ),
        migrations.AlterField(
            model_name='remonty',
            name='opis_remontu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remonty',
            name='wykonawca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Wykonawca'),
        ),
    ]
