# Generated by Django 5.1.1 on 2024-11-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0026_qrcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcode',
            options={'verbose_name': 'Kody QR', 'verbose_name_plural': 'Kody QR'},
        ),
    ]
